application:
  config:
    hostname: host.docker.internal #localhost
    eureka-port: 8761
eureka:
  instance:
    hostname: ${application.config.hostname}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${application.config.hostname}:${application.config.eureka-port}/eureka
spring:
  cloud:
    config:
      override-system-properties: false
  zipkin:
    baseUrl: http://${application.config.hostname}:9411/

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${application.config.hostname}:9411/api/v2/spans