spring:
  data:
    mongodb:
      username: pKanak
      password: pKanak
      host: ${application.config.hostname}
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090

logging:
  config: classpath:logback-spring.xml