spring:
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: default
        client-id: micro-services-client
        client-secret: aHjyBzvM29o1gWkec9nI4M3Lg7VpVd70
        token-uri: http://${application.config.hostname}:9099/realms/micro-services/protocol/openid-connect/token
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${application.config.hostname}:9099/realms/micro-services
      client:
        provider:
          keycloak:
            issuer-uri: http://${application.config.hostname}:9099/realms/micro-services
        registration:
          keycloak:
            client-id: micro-services-client
            client-secret: aHjyBzvM29o1gWkec9nI4M3Lg7VpVd70
            authorization-grant-type: client_credentials
  datasource:
    url: jdbc:postgresql://${application.config.hostname}:5432/order
    username: pKanak
    password: pKanak
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate #create-drop, create, update, validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: dockervm:9092
    producer:
      bootstrap-servers: dockervm:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.pk.ecommerce.kafka.OrderConfirmation
server:
  port: 8070

application:
  config:
    customer-url: http://${application.config.hostname}:8222/api/v1/customers #In next phase use url from api-gateway! api-gateway-port(8222) - 8090
    payment-url: http://${application.config.hostname}:8222/api/v1/payments #In next phase use url from api-gateway! api-gateway-port(8222) - 8060
    product-url: http://${application.config.hostname}:8222/api/v1/products #In next phase use url from api-gateway! api-gateway-port(8222) - 8050
    kafka:
      order-topic: order-topic

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO # TRACE DEBUG INFO WARN ERROR
    com:
      pk: INFO
    org:
      springframework:
        web:
          client: INFO

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]