application:
  config:
    hostname: host.docker.internal #localhost
spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://${application.config.hostname}:8888 # Get config from config-server