{
 "title": "Test Dashboard V0",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number Of Products",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_product_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number Of Categories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_category_count", "legendFormat": "__auto" }
   ]
  },
  { "title": "Api Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Purchase Products Count ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "api_call_purchase_products_counter_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}