spring:
  config:
    import: optional:configserver:http://localhost:8888 # Get config from config-server
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9099/realms/micro-services"