application:
  config:
    hostname: host.docker.internal #localhost
spring:
  config:
    import: optional:configserver:http://${application.config.hostname}:8888 # Get config from config-server
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${application.config.hostname}:9099/realms/micro-services"